import { create } from 'zustand';

export type Language = 'id' | 'en';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // Settings
    'settings.title': 'Pengaturan',
    'settings.account': 'Akun',
    'settings.editProfile': 'Edit Profil',
    'settings.editProfileDesc': 'Ubah nama dan telepon',
    'settings.changePhoto': 'Ganti Foto',
    'settings.changePhotoDesc': 'Perbarui foto profil',
    'settings.preferences': 'Preferensi',
    'settings.notifications': 'Notifikasi Push',
    'settings.notificationsDesc': 'Terima update pesanan',
    'settings.darkMode': 'Mode Gelap',
    'settings.darkModeDesc': 'Aktifkan tema gelap',
    'settings.other': 'Lainnya',
    'settings.language': 'Bahasa',
    'settings.privacy': 'Kebijakan Privasi',
    'settings.privacyDesc': 'Lihat kebijakan privasi',
    'settings.save': 'Simpan Perubahan',
    'settings.name': 'Nama',
    'settings.phone': 'Telepon',
    'settings.email': 'Email',
    'settings.emailHint': 'Email tidak bisa diubah',
    'settings.selectLanguage': 'Pilih Bahasa',

    // Profile
    'profile.title': 'Profil',
    'profile.manageAddress': 'Kelola Alamat',
    'profile.payment': 'Pembayaran',
    'profile.orders': 'Pesanan',
    'profile.offer': 'Penawaran',
    'profile.helpCenter': 'Pusat Bantuan',
    'profile.myAccount': 'Akun Saya',
    'profile.logout': 'Keluar',
    'profile.spend': 'Pengeluaran',

    // Home
    'home.categories': 'Kategori',
    'home.popularItems': 'Menu Populer',
    'home.seeAll': 'Lihat semua',

    // Cart
    'cart.title': 'Keranjang',
    'cart.empty': 'Keranjang Anda kosong',
    'cart.emptyDesc': 'Tambahkan item lezat untuk memulai',
    'cart.browseMenu': 'Lihat Menu',
    'cart.subtotal': 'Subtotal',
    'cart.checkout': 'Lanjut ke Checkout',

    // Menu
    'menu.title': 'Menu',
    'menu.search': 'Cari menu, kategori...',
    'menu.all': 'Semua',
    'menu.notFound': 'Menu tidak ditemukan',
    'menu.notFoundDesc': 'Coba cari dengan kata kunci lain',
    'menu.addedToCart': 'Ditambahkan ke keranjang',
    'menu.addedToCartDesc': 'ditambahkan ke keranjang Anda',
    'menu.removedFromFav': 'Dihapus dari favorit',
    'menu.addedToFav': 'Ditambahkan ke favorit',

    // Product Detail
    'product.notFound': 'Produk tidak ditemukan',
    'product.size': 'Ukuran',
    'product.addons': 'Tambahan',
    'product.specialInstructions': 'Instruksi Khusus',
    'product.specialPlaceholder': 'Ada permintaan khusus? (misal: kurang gula, ekstra panas)',
    'product.quantity': 'Jumlah',
    'product.total': 'Total',
    'product.addToCart': 'Tambah ke Keranjang',
    'product.addedToCart': 'Ditambahkan ke keranjang ✓',
    'product.reviews': 'ulasan',

    // Checkout
    'checkout.title': 'Checkout',
    'checkout.orderType': 'Tipe Pesanan',
    'checkout.dineIn': 'Dine In',
    'checkout.pickup': 'Pickup',
    'checkout.delivery': 'Delivery',
    'checkout.dineInDesc': 'Makan di tempat',
    'checkout.pickupDesc': 'Ambil di kasir',
    'checkout.deliveryDesc': 'Antar ke alamat',
    'checkout.tableNumber': 'Nomor Meja',
    'checkout.enterTable': 'Masukkan nomor meja Anda',
    'checkout.customerName': 'Nama Customer',
    'checkout.pickupTime': 'Jam Pengambilan',
    'checkout.recipientName': 'Nama Penerima',
    'checkout.phoneNumber': 'Nomor Telepon',
    'checkout.address': 'Alamat',
    'checkout.deliveryData': 'Data Pengiriman',
    'checkout.fillAddress': 'Isi alamat lengkap tujuan',
    'checkout.pickupFillData': 'Isi nama dan pilih jam pengambilan',
    'checkout.saved': 'Tersimpan',
    'checkout.saveAddress': 'Simpan alamat ini',
    'checkout.payment': 'Pembayaran',
    'checkout.selectPayment': 'Pilih metode pembayaran',
    'checkout.orderSummary': 'Ringkasan Pesanan',
    'checkout.deliveryFee': 'Ongkos Kirim',
    'checkout.free': 'Gratis',
    'checkout.placeOrder': 'Pesan Sekarang',
    'checkout.formIncomplete': 'Form tidak lengkap',
    'checkout.fillAllData': 'Mohon lengkapi semua data pengiriman',
    'checkout.addressSaved': 'Alamat tersimpan',
    'checkout.addressSavedDesc': 'Alamat berhasil disimpan untuk pengiriman berikutnya',
    'checkout.tableRequired': 'Nomor meja harus diisi',
    'checkout.nameRequired': 'Nama harus diisi',
    'checkout.selectPickupTime': 'Pilih jam pengambilan',

    // Order Success
    'orderSuccess.title': 'Pesanan Berhasil! 🎉',
    'orderSuccess.subtitle': 'Pesanan Anda telah dikonfirmasi dan sedang diproses',
    'orderSuccess.servedToTable': 'Disajikan ke meja Anda',
    'orderSuccess.readyIn': 'Siap diambil dalam',
    'orderSuccess.deliveryEstimate': 'Estimasi pengiriman',
    'orderSuccess.orderId': 'Order ID',
    'orderSuccess.orderType': 'Tipe Pesanan',
    'orderSuccess.tableNumber': 'Nomor Meja',
    'orderSuccess.pickupTime': 'Jam Pengambilan',
    'orderSuccess.total': 'Total',
    'orderSuccess.trackOrder': 'Lacak Pesanan',
    'orderSuccess.backHome': 'Kembali ke Home',
    'orderSuccess.toast': 'Pesanan berhasil dibuat! 🎉',
    'orderSuccess.toastDesc': 'sedang diproses',

    // Order Tracking
    'orderTracking.title': 'Lacak Pesanan',
    'orderTracking.notFound': 'Pesanan Tidak Ditemukan',
    'orderTracking.notFoundDesc': 'Pesanan ini tidak ada atau telah dihapus.',
    'orderTracking.backHome': 'Kembali ke Home',
    'orderTracking.liveTracking': 'Lacak Langsung',
    'orderTracking.orderItems': 'Item Pesanan',
    'orderTracking.subtotal': 'Subtotal',
    'orderTracking.deliveryFee': 'Ongkos Kirim',
    'orderTracking.total': 'Total',
    'orderTracking.deliveryAddress': 'Alamat Pengiriman',
    'orderTracking.completed': 'Pesanan Selesai!',
    'orderTracking.completedDesc': 'Terima kasih atas pesanan Anda. Nikmati kopinya!',

    // Orders
    'orders.title': 'Pesanan Saya',
    'orders.noOrders': 'Belum Ada Pesanan',
    'orders.noOrdersDesc': 'Mulai pesan kopi favoritmu!',
    'orders.activeOrders': 'Pesanan Aktif',
    'orders.pastOrders': 'Riwayat Pesanan',
    'orders.reorder': 'Beli Lagi',
    'orders.history': 'Riwayat',
    'orders.pending': 'Menunggu',
    'orders.confirmed': 'Dikonfirmasi',
    'orders.preparing': 'Disiapkan',
    'orders.ready': 'Siap',
    'orders.delivering': 'Diantar',
    'orders.completed': 'Selesai',
    'orders.cancelled': 'Dibatalkan',
    'orders.items': 'item',

    // Favorites
    'favorites.title': 'Favorit',
    'favorites.empty': 'Belum Ada Favorit',
    'favorites.emptyDesc': 'Mulai tambahkan item favorit Anda!',
    'favorites.addedToCart': 'Ditambahkan ke keranjang',
    'favorites.addedToCartDesc': 'ditambahkan ke keranjang Anda',

    // Reservations
    'reservations.title': 'Reservasi Meja',
    'reservations.selectDate': 'Pilih Tanggal',
    'reservations.selectTime': 'Pilih Waktu',
    'reservations.guests': 'Jumlah Tamu',
    'reservations.yourName': 'Nama Anda',
    'reservations.phone': 'Nomor Telepon',
    'reservations.confirm': 'Konfirmasi Reservasi',
    'reservations.missingInfo': 'Informasi belum lengkap',
    'reservations.fillAll': 'Harap isi semua field',
    'reservations.confirmed': 'Reservasi Dikonfirmasi!',
    'reservations.tableFor': 'Meja untuk',
    'reservations.yourReservations': 'Reservasi Anda',

    // Notifications
    'notifications.title': 'Notifikasi',
    'notifications.markAllRead': 'Tandai sudah dibaca',

    // Search
    'search.placeholder': 'Cari kopi, latte, espresso...',
    'search.results': 'hasil ditemukan',
    'search.noResults': 'Tidak ada hasil',
    'search.noResultsDesc': 'Kami tidak menemukan',
    'search.tryDifferent': 'Coba kata kunci lain.',
    'search.recent': 'Pencarian Terakhir',
    'search.clearAll': 'Hapus semua',
    'search.popular': 'Pencarian Populer',
    'search.browseCategories': 'Jelajahi Kategori',

    // Login
    'login.welcomeBack': 'Selamat Datang',
    'login.subtitle': 'Masuk untuk pesan kopi favoritmu',
    'login.email': 'Email',
    'login.emailPlaceholder': 'Masukkan email',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Masukkan password',
    'login.rememberMe': 'Ingat saya',
    'login.forgotPassword': 'Lupa Password?',
    'login.signIn': 'Masuk',
    'login.signingIn': 'Masuk...',
    'login.or': 'atau',
    'login.googleSignIn': 'Masuk dengan Google',
    'login.noAccount': 'Belum punya akun?',
    'login.register': 'Daftar',

    // Register
    'register.title': 'Buat Akun',
    'register.subtitle': 'Bergabung untuk menikmati kopi terbaik',
    'register.fullName': 'Nama Lengkap',
    'register.fullNamePlaceholder': 'Masukkan nama lengkap',
    'register.email': 'Email',
    'register.emailPlaceholder': 'Masukkan email',
    'register.password': 'Password',
    'register.passwordPlaceholder': 'Buat password',
    'register.confirmPassword': 'Konfirmasi Password',
    'register.confirmPlaceholder': 'Konfirmasi password',
    'register.submit': 'Daftar',
    'register.submitting': 'Membuat akun...',
    'register.terms': 'Dengan mendaftar, Anda menyetujui',
    'register.termsLink': 'Syarat & Ketentuan',
    'register.and': 'dan',
    'register.privacyLink': 'Kebijakan Privasi',
    'register.or': 'atau',
    'register.googleSignUp': 'Daftar dengan Google',
    'register.hasAccount': 'Sudah punya akun?',
    'register.login': 'Masuk',

    // Forgot Password
    'forgot.title': 'Lupa Password?',
    'forgot.subtitle': 'Masukkan email Anda dan kami akan mengirim link untuk reset password',
    'forgot.email': 'Email',
    'forgot.emailPlaceholder': 'Masukkan email',
    'forgot.submit': 'Kirim Link Reset',
    'forgot.submitting': 'Mengirim...',
    'forgot.successTitle': 'Email Terkirim!',
    'forgot.successDesc': 'Kami telah mengirim link reset password ke',
    'forgot.checkInbox': 'Periksa inbox atau folder spam Anda.',
    'forgot.resend': 'Kirim Ulang Email',
    'forgot.backToLogin': 'Kembali ke Login',

    // Bottom Nav
    'nav.home': 'Beranda',
    'nav.menu': 'Menu',
    'nav.cart': 'Keranjang',
    'nav.reserve': 'Reservasi',
    'nav.profile': 'Profil',

    // Toasts
    'toast.profileUpdated': 'Profil diperbarui',
    'toast.profileSaved': 'Profil berhasil disimpan.',
    'toast.photoUpdated': 'Foto profil diperbarui',
    'toast.photoFailed': 'Gagal mengunggah foto',
    'toast.langChanged': 'Bahasa diubah',
    'toast.error': 'Error',
    'toast.welcome': 'Selamat datang!',
    'toast.loginSuccess': 'Berhasil masuk.',
    'toast.loginFailed': 'Login gagal',
    'toast.wrongCredentials': 'Email atau password salah',
    'toast.emailNotVerified': 'Email belum diverifikasi',
    'toast.verifyEmail': 'Silakan cek inbox email Anda untuk verifikasi akun.',
    'toast.registerFailed': 'Registrasi gagal',
    'toast.checkEmail': 'Cek email Anda!',
    'toast.verificationSent': 'Kami telah mengirim email verifikasi. Silakan verifikasi sebelum login.',
    'toast.accountCreated': 'Akun berhasil dibuat.',
    'toast.emailSent': 'Email terkirim!',
    'toast.checkInbox': 'Periksa inbox email Anda untuk reset password.',
    'toast.fillAllFields': 'Harap isi semua field',
    'toast.passwordMismatch': 'Password tidak cocok',
    'toast.passwordShort': 'Password terlalu pendek',

    // Common
    'common.total': 'Total',
    'common.cancel': 'Batal',
    'common.confirm': 'Konfirmasi',
    'common.save': 'Simpan',
    'common.delete': 'Hapus',
    'common.edit': 'Ubah',
    'common.back': 'Kembali',
    'common.next': 'Selanjutnya',
    'common.loading': 'Memuat...',
    'common.uploading': 'Mengunggah...',
  },
  en: {
    // Settings
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.editProfile': 'Edit Profile',
    'settings.editProfileDesc': 'Change your name and phone',
    'settings.changePhoto': 'Change Photo',
    'settings.changePhotoDesc': 'Update your profile picture',
    'settings.preferences': 'Preferences',
    'settings.notifications': 'Push Notifications',
    'settings.notificationsDesc': 'Receive order updates',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Toggle dark theme',
    'settings.other': 'Other',
    'settings.language': 'Language',
    'settings.privacy': 'Privacy Policy',
    'settings.privacyDesc': 'View our privacy policy',
    'settings.save': 'Save Changes',
    'settings.name': 'Name',
    'settings.phone': 'Phone',
    'settings.email': 'Email',
    'settings.emailHint': 'Email cannot be changed',
    'settings.selectLanguage': 'Select Language',

    // Profile
    'profile.title': 'Profile',
    'profile.manageAddress': 'Manage Address',
    'profile.payment': 'Payment',
    'profile.orders': 'Orders',
    'profile.offer': 'Offer',
    'profile.helpCenter': 'Help Center',
    'profile.myAccount': 'My Account',
    'profile.logout': 'Log Out',
    'profile.spend': 'Spend',

    // Home
    'home.categories': 'Categories',
    'home.popularItems': 'Popular Items',
    'home.seeAll': 'See all',

    // Cart
    'cart.title': 'Cart',
    'cart.empty': 'Your cart is empty',
    'cart.emptyDesc': 'Add some delicious items to get started',
    'cart.browseMenu': 'Browse Menu',
    'cart.subtotal': 'Subtotal',
    'cart.checkout': 'Proceed to Checkout',

    // Menu
    'menu.title': 'Menu',
    'menu.search': 'Search menu, category...',
    'menu.all': 'All',
    'menu.notFound': 'Menu not found',
    'menu.notFoundDesc': 'Try searching with different keywords',
    'menu.addedToCart': 'Added to cart',
    'menu.addedToCartDesc': 'added to your cart',
    'menu.removedFromFav': 'Removed from favorites',
    'menu.addedToFav': 'Added to favorites',

    // Product Detail
    'product.notFound': 'Product not found',
    'product.size': 'Size',
    'product.addons': 'Add-ons',
    'product.specialInstructions': 'Special Instructions',
    'product.specialPlaceholder': 'Any special requests? (e.g., less sugar, extra hot)',
    'product.quantity': 'Quantity',
    'product.total': 'Total',
    'product.addToCart': 'Add to Cart',
    'product.addedToCart': 'Added to cart ✓',
    'product.reviews': 'reviews',

    // Checkout
    'checkout.title': 'Checkout',
    'checkout.orderType': 'Order Type',
    'checkout.dineIn': 'Dine In',
    'checkout.pickup': 'Pickup',
    'checkout.delivery': 'Delivery',
    'checkout.dineInDesc': 'Eat at restaurant',
    'checkout.pickupDesc': 'Pick up at counter',
    'checkout.deliveryDesc': 'Deliver to address',
    'checkout.tableNumber': 'Table Number',
    'checkout.enterTable': 'Enter your table number',
    'checkout.customerName': 'Customer Name',
    'checkout.pickupTime': 'Pickup Time',
    'checkout.recipientName': 'Recipient Name',
    'checkout.phoneNumber': 'Phone Number',
    'checkout.address': 'Address',
    'checkout.deliveryData': 'Delivery Details',
    'checkout.fillAddress': 'Fill in the complete delivery address',
    'checkout.pickupFillData': 'Fill name and select pickup time',
    'checkout.saved': 'Saved',
    'checkout.saveAddress': 'Save this address',
    'checkout.payment': 'Payment',
    'checkout.selectPayment': 'Select payment method',
    'checkout.orderSummary': 'Order Summary',
    'checkout.deliveryFee': 'Delivery Fee',
    'checkout.free': 'Free',
    'checkout.placeOrder': 'Place Order',
    'checkout.formIncomplete': 'Form incomplete',
    'checkout.fillAllData': 'Please fill in all delivery details',
    'checkout.addressSaved': 'Address saved',
    'checkout.addressSavedDesc': 'Address saved for future deliveries',
    'checkout.tableRequired': 'Table number is required',
    'checkout.nameRequired': 'Name is required',
    'checkout.selectPickupTime': 'Select pickup time',

    // Order Success
    'orderSuccess.title': 'Order Successful! 🎉',
    'orderSuccess.subtitle': 'Your order has been confirmed and is being processed',
    'orderSuccess.servedToTable': 'Served to your table',
    'orderSuccess.readyIn': 'Ready for pickup in',
    'orderSuccess.deliveryEstimate': 'Estimated delivery',
    'orderSuccess.orderId': 'Order ID',
    'orderSuccess.orderType': 'Order Type',
    'orderSuccess.tableNumber': 'Table Number',
    'orderSuccess.pickupTime': 'Pickup Time',
    'orderSuccess.total': 'Total',
    'orderSuccess.trackOrder': 'Track Order',
    'orderSuccess.backHome': 'Back to Home',
    'orderSuccess.toast': 'Order placed successfully! 🎉',
    'orderSuccess.toastDesc': 'is being processed',

    // Order Tracking
    'orderTracking.title': 'Track Order',
    'orderTracking.notFound': 'Order Not Found',
    'orderTracking.notFoundDesc': "This order doesn't exist or has been removed.",
    'orderTracking.backHome': 'Back to Home',
    'orderTracking.liveTracking': 'Live Tracking',
    'orderTracking.orderItems': 'Order Items',
    'orderTracking.subtotal': 'Subtotal',
    'orderTracking.deliveryFee': 'Delivery Fee',
    'orderTracking.total': 'Total',
    'orderTracking.deliveryAddress': 'Delivery Address',
    'orderTracking.completed': 'Order Completed!',
    'orderTracking.completedDesc': 'Thank you for your order. Enjoy your coffee!',

    // Orders
    'orders.title': 'My Orders',
    'orders.noOrders': 'No Orders Yet',
    'orders.noOrdersDesc': 'Start ordering your favorite coffee!',
    'orders.activeOrders': 'Active Orders',
    'orders.pastOrders': 'Past Orders',
    'orders.reorder': 'Reorder',
    'orders.history': 'History',
    'orders.pending': 'Pending',
    'orders.confirmed': 'Confirmed',
    'orders.preparing': 'Preparing',
    'orders.ready': 'Ready',
    'orders.delivering': 'On the Way',
    'orders.completed': 'Completed',
    'orders.cancelled': 'Cancelled',
    'orders.items': 'item',

    // Favorites
    'favorites.title': 'Favorites',
    'favorites.empty': 'No Favorites Yet',
    'favorites.emptyDesc': 'Start adding your favorite items!',
    'favorites.addedToCart': 'Added to cart',
    'favorites.addedToCartDesc': 'added to your cart',

    // Reservations
    'reservations.title': 'Reserve a Table',
    'reservations.selectDate': 'Select Date',
    'reservations.selectTime': 'Select Time',
    'reservations.guests': 'Number of Guests',
    'reservations.yourName': 'Your name',
    'reservations.phone': 'Phone number',
    'reservations.confirm': 'Confirm Reservation',
    'reservations.missingInfo': 'Missing information',
    'reservations.fillAll': 'Please fill all fields',
    'reservations.confirmed': 'Reservation Confirmed!',
    'reservations.tableFor': 'Table for',
    'reservations.yourReservations': 'Your Reservations',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all read',

    // Search
    'search.placeholder': 'Search coffee, latte, espresso...',
    'search.results': 'results found',
    'search.noResults': 'No results found',
    'search.noResultsDesc': "We couldn't find",
    'search.tryDifferent': 'Try a different search term.',
    'search.recent': 'Recent Searches',
    'search.clearAll': 'Clear all',
    'search.popular': 'Popular Searches',
    'search.browseCategories': 'Browse Categories',

    // Login
    'login.welcomeBack': 'Welcome Back',
    'login.subtitle': 'Sign in to order your favorite coffee',
    'login.email': 'Email',
    'login.emailPlaceholder': 'Enter email',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot Password?',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.or': 'or',
    'login.googleSignIn': 'Sign in with Google',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Register',

    // Register
    'register.title': 'Create Account',
    'register.subtitle': 'Join us to enjoy the best coffee',
    'register.fullName': 'Full Name',
    'register.fullNamePlaceholder': 'Enter full name',
    'register.email': 'Email',
    'register.emailPlaceholder': 'Enter email',
    'register.password': 'Password',
    'register.passwordPlaceholder': 'Create password',
    'register.confirmPassword': 'Confirm Password',
    'register.confirmPlaceholder': 'Confirm password',
    'register.submit': 'Register',
    'register.submitting': 'Creating account...',
    'register.terms': 'By signing up, you agree to our',
    'register.termsLink': 'Terms & Conditions',
    'register.and': 'and',
    'register.privacyLink': 'Privacy Policy',
    'register.or': 'or',
    'register.googleSignUp': 'Sign up with Google',
    'register.hasAccount': 'Already have an account?',
    'register.login': 'Sign In',

    // Forgot Password
    'forgot.title': 'Forgot Password?',
    'forgot.subtitle': "Enter your email and we'll send you a reset link",
    'forgot.email': 'Email',
    'forgot.emailPlaceholder': 'Enter email',
    'forgot.submit': 'Send Reset Link',
    'forgot.submitting': 'Sending...',
    'forgot.successTitle': 'Email Sent!',
    'forgot.successDesc': "We've sent a password reset link to",
    'forgot.checkInbox': 'Check your inbox or spam folder.',
    'forgot.resend': 'Resend Email',
    'forgot.backToLogin': 'Back to Login',

    // Bottom Nav
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.cart': 'Cart',
    'nav.reserve': 'Reserve',
    'nav.profile': 'Profile',

    // Toasts
    'toast.profileUpdated': 'Profile updated',
    'toast.profileSaved': 'Your profile has been saved.',
    'toast.photoUpdated': 'Profile photo updated',
    'toast.photoFailed': 'Failed to upload photo',
    'toast.langChanged': 'Language changed',
    'toast.error': 'Error',
    'toast.welcome': 'Welcome!',
    'toast.loginSuccess': 'Successfully signed in.',
    'toast.loginFailed': 'Login failed',
    'toast.wrongCredentials': 'Wrong email or password',
    'toast.emailNotVerified': 'Email not verified',
    'toast.verifyEmail': 'Please check your inbox to verify your account.',
    'toast.registerFailed': 'Registration failed',
    'toast.checkEmail': 'Check your email!',
    'toast.verificationSent': 'We sent a verification email. Please verify before signing in.',
    'toast.accountCreated': 'Account created successfully.',
    'toast.emailSent': 'Email sent!',
    'toast.checkInbox': 'Check your inbox for password reset.',
    'toast.fillAllFields': 'Please fill all fields',
    'toast.passwordMismatch': 'Passwords do not match',
    'toast.passwordShort': 'Password too short',

    // Common
    'common.total': 'Total',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.loading': 'Loading...',
    'common.uploading': 'Uploading...',
  },
};

export const useLanguageStore = create<LanguageStore>()((set, get) => ({
  language: (localStorage.getItem('app-language') as Language) || 'id',
  setLanguage: (lang: Language) => {
    localStorage.setItem('app-language', lang);
    set({ language: lang });
  },
  t: (key: string) => {
    const { language } = get();
    return translations[language]?.[key] || key;
  },
}));
